### PR TITLE
Mongodb deploy mongodb atlas

### PR DESCRIPTION
**Pull request by cfnelson**
PR to add a recommendation to use MongoDB Atlas for hosting your MongoDB.
Similar PR made on the Meteor Guide which has been accepted and merged: https://github.com/meteor/guide/pull/609

**Changes made:**
 - Added recommendation for MongoDB Atlas as a MongoDB hosting service.
 - Added hyperlink to detailed step-by-step guide to setting up MongoDB Atlas for a Meteor app deployed with Galaxy.
 - Removed unnecessary whitespaces from end of lines.

@julianeon Let me know if there is anything I can do to help this PR get accepted and merged. 🙂

### CODE REVIEW

**Comment by julianeon** [comment]
Thanks for sharing this! I'll take a look at this and get back to you by mid-week.

**Comment by cfnelson** [comment]
Thanks, 😄  let me know if there is anything else I need to do for this PR.

**Comment by julianeon** [comment]
I changed OK GROW! to OK Grow! and change language to better match
previous line (also slightly adjusted) in the MongoDB article, and removed the OK Grow line from the Deploy Quickstart article since all other references were to Galaxy articles. 

Will now share w/the team for review.

**Comment by julianeon** [comment]
I see now that it's OK GROW! after checking the website - that looks good.

**Comment by cfnelson** [comment]
@julianeon Thanks! Beat me to letting you know about the small change 😄 . Thanks for reviewing this.

**Comment by julianeon** [comment]
Approved. Thank you Mr. Nelson!

**Pull request merged**
