### PR TITLE
cdn: suggest using _g_app_v

### PR DESCRIPTION
**Pull request by glasser**

### CODE REVIEW

**Comment by julianeon** [comment]
LGTM!

**Comment by dburles** [comment]
It's not super apparent that `GALAXY_APP_VERSION_ID` isn't actually available on the client by referencing `process.env.GALAXY_APP_VERSION_ID`.

**Comment by glasser** [comment]
@dburles Hmm, good point.  The API we're using here is a server-specific API, and in general environment variables aren't available in the client (only a few very specific ones like NODE_ENV are copied over — it would be a security disaster if most of them were!). Do you have a specific improvement that would have made the docs more clear for you?

**Comment by dburles** [comment]
Well, I think it seems ideal to also cache assets by deployment version, as the docs mention. Yet it's made a bit more difficult with it only being available on the server. I really think it should be exposed to the client in some way. Ideally an environment variable. As often components that may need to directly reference this value are used in many contexts outside of Meteor, e.g Storybook / Jest.

**Comment by glasser** [comment]
Yeah, that makes sense! You'd want to make that value available to the client via something like DDP or Meteor.settings.public. If you have a good way of describing this, feel free to open a PR against this repo!

**Comment by dburles** [comment]
Will do, thanks @glasser

**Pull request merged**
